CREATE DATABASE `drweb` /*!40100 COLLATE 'utf8mb4_unicode_ci' */;
CREATE USER 'webuser'@'localhost' IDENTIFIED BY '111111';
GRANT USAGE ON *.* TO 'webuser'@'localhost';
GRANT SELECT, EXECUTE, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `drweb`.* TO 'webuser'@'localhost' WITH GRANT OPTION;
USE drweb;
CREATE TABLE `topic` (
	`id` MEDIUMINT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
	`title` TINYTEXT NOT NULL,
	`description` MEDIUMTEXT NOT NULL,
	`author` TINYTEXT NOT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;
FLUSH PRIVILEGES;